#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Clover->macOS" {
	insmod part_gpt
	insmod fat
	set root="hd0,gpt1"
	chainloader /EFI/CLOVER/PreLoader.efi}

#menuentry "Solus" {
#	insmod part_gpt
#	insmod fat
#	set root="hd0,gpt1"
#	chainloader /EFI/goofiboot/goofibootx64.efi}

menuentry "Qubes" {
	insmod part-gpt
	insmod fat
	set root="hd0,gpt1"
	chainloader /EFI/qubes/xen.efi}
